// Centralized product data - single source of truth for store items
import { Product } from "@/lib/types";

export const products: Product[] = [
  { 
    id: "1", 
    title: "VINTAGE", 
    color: "bg-[#e76f51]", 
    accent: "bg-[#264653]", 
    subtitle: "Vacuum Pups", 
    price: 12.00, 
    difficulty: 2, 
    age: "All Ages", 
    category: "VINTAGE",
    description: "A nostalgic journey into the world of retro-futuristic household companions. Vacuum Pups explores the bond between machines and their canine counterparts in a 1950s atomic age setting.",
    discount_percent: 0,
    is_published: true
  },
  { 
    id: "2", 
    title: "SCI-FI", 
    color: "bg-[#2a9d8f]", 
    accent: "bg-[#e9c46a]", 
    subtitle: "Star Drifter", 
    price: 15.00, 
    difficulty: 4, 
    age: "Teens+", 
    category: "SCI-FI",
    description: "Drift through the cosmos with this intricate collection of starships, space stations, and alien landscapes. Designed for advanced colorists seeking a challenge.",
    discount_percent: 0,
    is_published: true
  },
  { 
    id: "3", 
    title: "HORROR", 
    color: "bg-[#1a1a1a]", 
    accent: "bg-[#e63946]", 
    subtitle: "Night Terror", 
    price: 6.66, 
    difficulty: 5, 
    age: "Adults", 
    category: "HORROR",
    description: "Face your fears. A collection of nightmares and eldritch horrors generated by the machine mind. Not for the faint of heart.",
    discount_percent: 0,
    is_published: true
  },
  { 
    id: "4", 
    title: "FANTASY", 
    color: "bg-[#457b9d]", 
    accent: "bg-[#a8dadc]", 
    subtitle: "Realm Walker", 
    price: 14.00, 
    difficulty: 3, 
    age: "Teens+", 
    category: "FANTASY",
    description: "Step into a realm of magic and mystery. Knights, dragons, and ancient ruins await your creative touch.",
    discount_percent: 0,
    is_published: true
  },
  { 
    id: "5", 
    title: "NOSTALGIA", 
    color: "bg-[#f4a261]", 
    accent: "bg-[#2a9d8f]", 
    subtitle: "Retrowave", 
    price: 11.00, 
    difficulty: 1, 
    age: "All Ages", 
    category: "NOSTALGIA",
    description: "Synthesizers, neon lights, and fast cars. Relive the 80s with this vibrant collection of retrowave aesthetics.",
    discount_percent: 0,
    is_published: true
  },
  { 
    id: "6", 
    title: "CLASSICS", 
    color: "bg-[#6d597a]", 
    accent: "bg-[#b56576]", 
    subtitle: "The Origin", 
    price: 18.00, 
    difficulty: 3, 
    age: "All Ages", 
    category: "CLASSICS",
    description: "Where it all began. The original sketches and concepts that started the Machine Brain project.",
    discount_percent: 0,
    is_published: true
  },
  { 
    id: "7", 
    title: "MECHA", 
    color: "bg-[#2b2d42]", 
    accent: "bg-[#8d99ae]", 
    subtitle: "Iron Giant", 
    price: 16.00, 
    difficulty: 5, 
    age: "Teens+", 
    category: "SCI-FI",
    description: "Giant robots and mechanical marvels. Highly detailed schematics and battle scenes for the mecha enthusiast.",
    discount_percent: 0,
    is_published: true
  },
  { 
    id: "8", 
    title: "BOTANICAL", 
    color: "bg-[#006d77]", 
    accent: "bg-[#83c5be]", 
    subtitle: "Flora", 
    price: 13.00, 
    difficulty: 2, 
    age: "All Ages", 
    category: "NATURE",
    description: "Explore the synthetic flora of a terraformed world. Alien plants and bio-mechanical flowers.",
    discount_percent: 0,
    is_published: true
  },
  { 
    id: "9", 
    title: "HOLIDAY", 
    color: "bg-[#e63946]", 
    accent: "bg-[#2a9d8f]", 
    subtitle: "Cosmic Xmas", 
    price: 15.00, 
    difficulty: 3, 
    age: "All Ages", 
    category: "HOLIDAY",
    description: "Celebrate the season with our exclusive holiday coloring collection. The perfect digital detox gift for you and your loved ones featuring festive sci-fi landscapes.",
    discount_percent: 0,
    is_published: true
  },
];

export const categories = ["ALL", "VINTAGE", "SCI-FI", "HORROR", "FANTASY", "NOSTALGIA", "CLASSICS", "NATURE", "HOLIDAY"] as const;

export type Category = typeof categories[number];

// Helper function to get a product by ID
export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

// Helper function to filter products by category
export function getProductsByCategory(category: Category): Product[] {
  if (category === "ALL") return products;
  return products.filter(p => p.category === category || p.title === category);
}
